Repository Romket/FlashBackClient, pull requests merged in 2025-02, with the labels that each got.

#13 Implement fully working listener
  .clang-format
  .gitignore
  TODO.md
  configs/flashbackclient/flashbackclient.yaml
  docs/CONFIGS.md
  include/flashbackclient/listener.h
  include/flashbackclient/scheduler.h
  src/listener/inotify/inotify_listener.cpp
  src/main.cpp
  src/scheduler.cpp
  src/target.cpp
Labels: documentation, enhancement

#16 Epoll integration
  include/flashbackclient/listener.h
  src/listener/inotify/inotify_listener.cpp
  src/listener/inotify/inotify_listener.h
Labels: enhancement, performance

#17 Listener now flags main thread
  TODO.md
  include/flashbackclient/scheduler.h
  src/listener/inotify/inotify_listener.cpp
  src/main.cpp
  src/scheduler.cpp
Labels: performance

#19 Listener Owners
  include/flashbackclient/listener.h
  include/flashbackclient/scheduler.h
  include/flashbackclient/target.h
  src/configs.cpp
  src/listener/inotify/inotify_listener.cpp
  src/listener/inotify/inotify_listener.h
  src/scheduler.cpp
  src/target.cpp
Labels: enhancement, performance

#20 Leg
  include/flashbackclient/configs.h
  include/flashbackclient/defs.h
  include/flashbackclient/logger.h
  include/flashbackclient/managers/rulemanager.h
  include/flashbackclient/managers/settingmanager.h
  include/flashbackclient/scheduler.h
  include/flashbackclient/service_locator.h
  include/flashbackclient/trigger.h
  src/listener/inotify/inotify_listener.cpp
  src/listener/platform_listener.h
  src/logger.cpp
  src/main.cpp
  src/managers/rulemanager.cpp
  src/managers/settingmanager.cpp
  src/scheduler.cpp
  src/target.cpp
Labels: enhancement

#21 Clean shutdown
  CMakeLists.txt
  include/flashbackclient/configs.h
  include/flashbackclient/managers/rulemanager.h
  include/flashbackclient/managers/settingmanager.h
  include/flashbackclient/scheduler.h
  include/flashbackclient/service_locator.h
  include/flashbackclient/signal_handler.h
  include/flashbackclient/target.h
  src/configs.cpp
  src/listener/inotify/inotify_listener.cpp
  src/main.cpp
  src/managers/rulemanager.cpp
  src/managers/settingmanager.cpp
  src/scheduler.cpp
  src/signal_handler.cpp
  src/target.cpp
Labels: enhancement

#22 Signal handler improvements
  .clang-format
  include/flashbackclient/signal_handler.h
  src/main.cpp
  src/signal_handler.cpp
Labels: enhancement

#24 Path ignores
  configs/flashbackclient/targets/example.yaml
  docs/CONFIGS.md
  include/flashbackclient/logger.h
  include/flashbackclient/managers/settingmanager.h
  include/flashbackclient/service_locator.h
  include/flashbackclient/target.h
  src/listener/inotify/inotify_listener.cpp
  src/logger.cpp
  src/main.cpp
  src/managers/rulemanager.cpp
  src/managers/settingmanager.cpp
  src/scheduler.cpp
  src/signal_handler.cpp
  src/target.cpp
Labels: documentation, enhancement
